# GoReleaser configuration for Seedfast CLI
# Documentation: https://goreleaser.com
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: seedfast
    main: ./main.go
    binary: seedfast
    env:
      - CGO_ENABLED=0  # Static binary - no C dependencies!
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X seedfast/cli/cmd.Version={{.Version}}
    flags:
      - -trimpath

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

brews:
  - name: seedfast
    repository:
      owner: argon-it
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

    # Path in the tap repository
    directory: Formula

    # Metadata
    homepage: "https://seedfa.st"
    description: "AI-powered PostgreSQL database seeding tool"
    license: "MIT"

    # Commit settings
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore: update {{ .ProjectName }} to {{ .Tag }}"

    # No runtime dependencies - standalone binary!
    # This means users DON'T need Xcode/CLT!

    # Installation
    install: |
      bin.install "seedfast"

    # Test that binary works
    test: |
      system "#{bin}/seedfast", "version"

    # Extra information
    caveats: |
      Run `seedfast login` to authenticate with the backend service.
      Then use `seedfast connect` to configure your database connection.
      Finally, run `seedfast seed` to start seeding your database.

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: argon-it
    name: seedfast-cli
