// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: internal/bridge/proto/database_bridge.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatabaseBridge_RunSeeding_FullMethodName = "/database_bridge.DatabaseBridge/RunSeeding"
)

// DatabaseBridgeClient is the client API for DatabaseBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Main service for client connections and agent control
type DatabaseBridgeClient interface {
	// Bidirectional stream: Client sends SQL responses, Server sends SQL requests and UI events
	RunSeeding(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type databaseBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseBridgeClient(cc grpc.ClientConnInterface) DatabaseBridgeClient {
	return &databaseBridgeClient{cc}
}

func (c *databaseBridgeClient) RunSeeding(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DatabaseBridge_ServiceDesc.Streams[0], DatabaseBridge_RunSeeding_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatabaseBridge_RunSeedingClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// DatabaseBridgeServer is the server API for DatabaseBridge service.
// All implementations must embed UnimplementedDatabaseBridgeServer
// for forward compatibility.
//
// Main service for client connections and agent control
type DatabaseBridgeServer interface {
	// Bidirectional stream: Client sends SQL responses, Server sends SQL requests and UI events
	RunSeeding(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedDatabaseBridgeServer()
}

// UnimplementedDatabaseBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabaseBridgeServer struct{}

func (UnimplementedDatabaseBridgeServer) RunSeeding(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method RunSeeding not implemented")
}
func (UnimplementedDatabaseBridgeServer) mustEmbedUnimplementedDatabaseBridgeServer() {}
func (UnimplementedDatabaseBridgeServer) testEmbeddedByValue()                        {}

// UnsafeDatabaseBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseBridgeServer will
// result in compilation errors.
type UnsafeDatabaseBridgeServer interface {
	mustEmbedUnimplementedDatabaseBridgeServer()
}

func RegisterDatabaseBridgeServer(s grpc.ServiceRegistrar, srv DatabaseBridgeServer) {
	// If the following call pancis, it indicates UnimplementedDatabaseBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatabaseBridge_ServiceDesc, srv)
}

func _DatabaseBridge_RunSeeding_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DatabaseBridgeServer).RunSeeding(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DatabaseBridge_RunSeedingServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// DatabaseBridge_ServiceDesc is the grpc.ServiceDesc for DatabaseBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabaseBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "database_bridge.DatabaseBridge",
	HandlerType: (*DatabaseBridgeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunSeeding",
			Handler:       _DatabaseBridge_RunSeeding_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/bridge/proto/database_bridge.proto",
}
